apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-k8s
  name: springboot-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-k8s
  template:
    metadata:
      labels:
        app: springboot-k8s
    spec:
      containers:
      - name: wissen-docker-ecr-repo
        image: 303486850858.dkr.ecr.ap-south-1.amazonaws.com/wissen-docker-ecr-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata: 
  name: springboot-k8s-svc
spec:
  selector:
    app: springboot-k8s
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort