apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-k8s
  name: springboot-k8s
spec:
  replicas: 4
  selector:
    matchLabels:
      app: springboot-k8s
  template:
    metadata:
      labels:
        app: springboot-k8s
    spec:
      containers:
      - name: wissen-docker-ecr-repo
        image: 303486850858.dkr.ecr.ap-south-1.amazonaws.com/wissen-docker-ecr-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-k8s
    k8s-app: springboot-k8s
  name: springboot-k8s
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-k8s